# GitHub Pages'e dağıtım için basit bir iş akışı
name: Deploy to GitHub Pages

on:
  # `main` dalına yapılan her push işleminde çalışır
  push:
    branches: [ "main" ]
  
  # Bu satır, bu iş akışını Actions sekmesinden manuel olarak çalıştırmanıza olanak tanır
  workflow_dispatch:

# GITHUB_TOKEN için dağıtım izinlerini ayarla
permissions:
  contents: read
  pages: write
  id-token: write

# Aynı anda sadece bir dağıtıma izin ver
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Tek dağıtım işi
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # dist klasörünü yükle
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4